const CATALOG = [
    {
    id: "el1",
    img: "../img/1.png",
    title: "Apple BYZ S8521",
    price: "2927",
    rate: 4.7,
    },
        {
    id: "el2",
    img: "../img/2.png",
    title: "Apple EarPods",
    price: "2927",
    rate: 4.5,
    },
        {
            id: "el3",
    img: "../img/3.png",
    title: "Apple EarPods",
    price: "2927",
    rate: 4.5,
    },
        {
            id: "el4",
    img: "../img/1.png",
    title: "Apple BYZ S8521",
    price: "2927",
    rate: 4.7,
    },
        {
            id: "el5",
    img: "../img/2.png",
    title: "Apple EarPods",
    price: "2927",
    rate: 4.5,
    },
        {
            id: "el6",
    img: "../img/3.png",
    title: "Apple EarPods",
    price: "2927",
    rate: 4.5,
    },
        {
            id: "el7",
    img: "../img/4.png",
    title: "Apple AirPods",
    price: "9527",
    rate: 4.7,
    },
        {
            id: "el8",
    img: "../img/5.png",
    title: "GERLAX GH-04",
    price: "6527",
    rate: 4.7,
    },
        {
            id: "el9",
    img: "../img/6.png",
    title: "BOROFONE BO4",
    price: "7527",
    rate: 4.7,
    },
]
